#!/bin/sh

# Copyright (C) 2018 Nikolas De Giorgis <nikolas.degiorgis@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

IFS=
result=`speedtest++ --output text`
DOWN=`echo $result | grep DOWN | awk -F"=" '{print $NF}'`
UP=`echo $result | grep UP | awk -F"=" '{print $NF}'`

LABEL=${LABEL:""}
DOWN_LABEL=${DOWN_LABEL:""}
UP_LABEL=${UP_LABEL:""}
WARNING=""

if [ "$UP" -eq "0" ] || [ "$DOWN" -eq "0" ] || [ "$DOWN" -eq "" ] || [ "$UP" -eq "" ];
then
    notify-send "net speeds: $UP/$DOWN at $(date +%T)."
    WARNING="WARNING: "
fi

echo $WARNING$(date +%D) $(date +%T) $DOWN_LABEL$DOWN "MB/s" $UP_LABEL$UP "MB/s" >> ~/speedtest-output.txt
echo $LABEL $DOWN_LABEL$DOWN "MB/s" $UP_LABEL$UP "MB/s"
